version : "2"

services :

  rabbit : 
    image : rabbitmq:3-management
    ports :
      - "15672:15672"

  db :
    build :
      context : db

    depends_on: 
      - rabbit

    environment : 
      RABBIT_USER : "guest"
      RABBIT_PASSWORD : "guest"
      RABBIT_HOST : "rabbit"
      RABBIT_PORT : "5672"

  blockchain : 
    build : 
      context : blockchain 

    depends_on: 
      - rabbit 

    environment : 
      RABBIT_USER : "guest" 
      RABBIT_PASSWORD : "guest"
      RABBIT_HOST : "rabbit"
      RABBIT_PORT : "5672"

  gateway : 

    build : 
      context : gateway

    depends_on:
      - rabbit 
    
    ports :
      - "8000:8000"

    environment : 
      RABBIT_USER : "guest" 
      RABBIT_PASSWORD : "guest"
      RABBIT_HOST : "rabbit"
      RABBIT_PORT : "5672"
